name: 'taxi_co2'
version: '1.0.0'
config-version: 2

profile: 'taxi_co2'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

seeds:
  taxi_co2:
    vehicle_emissions:
      +file: "vehicle_emissions.csv"
      +schema: main
      +quote_columns: true

models:
  taxi_co2:
    staging:
      +materialized: table
    transform:
      +materialized: table
